version: "3.7"

volumes:
  timescale-data:
    name: compose_timescale-data

networks:
  ocean_default:
    driver: overlay
    attachable: true
  outside:
    name: "host"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1

  frontend:
    image: ocean-frontend:5

  api:
    image: ocean-backend:3
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: node dist
    environment:
      - POSTGRES_HOST=timescaledb
    deploy:
      labels:
        repository: "cormind-concrete"

  timescaledb:
    image: timescale/timescaledb:1.5.1-pg10
    command: "-c 'max_connections=5000'"
    ports:
      - 5432:5432
    volumes:
      - timescale-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
